[package]
name = "quizzes"
version = "0.1.0"
edition = "2024"

[lib]
name = "quizzes"
path = "src/quizzes.rs"

[dependencies]
chrono = "0.4.38"
futures = "0.3.31"

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

libs = { path = "../libs" }

book = { path = "../../crypto-n-rust/src/libs/book" }

