[package]
name = "b_table"
version = "0.1.0"
edition = "2024"

[dependencies]

chrono = "0.4.38"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

book = { path = "../../../../crypto-n-rust/src/libs/book" }
libs = { path = "../../../libs" }
quiz01 = { path = ".." }
